"""
Django settings for fincrest project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from fincrest.utils.keyvault import get_secret  # ✅ Import Key Vault Utility

# Base Directory
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔒 Load Secrets from Azure Key Vault
SECRET_KEY = get_secret("DJANGO-SECRET-KEY")  # ✅ Fetch secret from Key Vault
if not SECRET_KEY:
    raise ValueError("❌ SECRET_KEY is missing from Key Vault!")

DEBUG = os.getenv("DEBUG", "False").lower() == "true"  # ✅ Default False in production

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "*").split(",")  # ✅ Load from env

# 🚀 Installed Applications
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.ai_engine",         # ✅ Ensure these match your app folders
    "apps.azure_integration",
    "apps.data_connectors",
    "apps.financial_core",
]

# 🚀 Middleware
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fincrest.urls"

# 🚀 Templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # ✅ Ensure a "templates" folder exists
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "fincrest.wsgi.application"

# 🚀 **DATABASE: Azure PostgreSQL**
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": get_secret("DB-NAME"),
        "USER": get_secret("DB-USER"),
        "PASSWORD": get_secret("DB-PASSWORD"),
        "HOST": get_secret("DB-HOST"),
        "PORT": "5432",  # ✅ Default PostgreSQL port
    }
}

if not DATABASES["default"]["NAME"]:
    raise ValueError("❌ Database configuration is missing! Check Key Vault settings.")

# 🔒 Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# 🌍 Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# 🖼 Static & Media Files
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# 🚀 Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
